import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Footer, Navbar } from "@/components";
import "./globals.css";


const montserrat = Montserrat({
  display: 'swap',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthStack = typeof window !== 'undefined' && window.location.pathname.includes('login');

  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          {/* Top Navbar */}
          {!isAuthStack && <Navbar />}

          {/* Main Content */}
          <main className={`${!isAuthStack ? 'pt-20 -mb-20 flex-grow' : 'pt-0'} bg-gradient-to-br from-[#FFE5D9] via-[#E6E6FA] to-[#F5DEB3] `}>
            {children}
          </main>

          {/* Footer */}
          {!isAuthStack && <Footer />}
        </div>
      </body>
    </html>
  );
}
